# Generated by Django 4.2 on 2023-04-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_hackathon_end_date_alter_hackathon_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="description",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="hackathon",
            name="github_url",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="hackathon",
            name="other_url",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
