# Generated by Django 4.2 on 2023-04-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_hackathon_github_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="submission",
            field=models.TextField(),
        ),
    ]
